CREATE TABLE roles (
       id BIGSERIAL PRIMARY KEY,
       nome VARCHAR(50) NOT NULL UNIQUE
);
/*CRIA ROLES BÁSICOS FUTURAMENTE SERÁ CRIADO CADASTRO VIA SISTEMA*/
INSERT INTO roles (nome) VALUES ('CLIENTE');
INSERT INTO roles (nome) VALUES ('FUNCIONÁRIO');
INSERT INTO roles (nome) VALUES ('ADMINISTRADOR');
INSERT INTO roles (nome) VALUES ('MEDICO VETERINÁRIO');